version: "3.7"
services:
  app_proxy:
    environment:
      # Formato correto para o Umbrel
      APP_HOST: chevereto-server_1
      APP_PORT: 80
    
  server:
    image: chevereto/chevereto:latest
    user: "1000:1000"
    init: true
    networks:
      - chevereto
    volumes:
      - storage:/var/www/html/images/
    restart: unless-stopped
    depends_on:
      - db
    environment:
      CHEVERETO_DB_HOST: db
      CHEVERETO_DB_USER: chevereto
      CHEVERETO_DB_PASS: user_database_password
      CHEVERETO_DB_PORT: 3306
      CHEVERETO_DB_NAME: chevereto
      CHEVERETO_HOSTNAME: localhost
      CHEVERETO_HOSTNAME_PATH: /
      CHEVERETO_HTTPS: 0
      CHEVERETO_MAX_POST_SIZE: 2G
      CHEVERETO_MAX_UPLOAD_SIZE: 2G

  db:
    image: mariadb:jammy
    networks:
      - chevereto
    volumes:
      - database:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: chevereto
      MYSQL_USER: chevereto
      MYSQL_PASSWORD: user_database_password

volumes:
  database:
  storage:

networks:
  chevereto:
