version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: chevereto-server_1
      APP_PORT: 8888
      PROXY_AUTH_ADD = "false"
  
  server:
    image: chevereto/chevereto:latest
    volumes:
      - storage:/var/www/html/images/
    restart: always
